### ISSUE TITLE
jiraf new cmd no longer creates a project - returns usage information.

### ISSUE THREAD

**Issue by conifer-dev** [gweithio/jiraf#1]
## Context

When passing the command to build a new project via Jiraf it will return the usage information and no project is created nor error output.

> jiraf new -name:"ExampleProject" -type:exe
> 
>      usage: jiraf new -name:"project name" -type:exe
> 
>     -name:"project name" - [required] The name of the package
> 
>     -type:exe - [required] The project type, exe or lib
> 
>     -author:"author name" - [optional] The author of the project
> 
>     -version:"0.1" - [optional] The initial project version
> 

* Operating System, Odin Version, Jiraf version
* Arch Linux, odin version dev-2022-05:33895b6d, I assume 0.3.3 (version that provided get cmd)

## Expected Behavior

New project is created on cmd run.

## Current Behavior

usage information is returned and no project is created nor error output.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Git Clone & Build
2. Run the jiraf new cmd with passed params
3. See the usage output print out and no new project created.

### Failure Logs

No logs printed out.

**Comment by gweithio** [comment]
Fix now in master
