### ISSUE TITLE
Provide a version cmd

### ISSUE THREAD

**Issue by conifer-dev** [gweithio/jiraf#2]
Sorry for not using any template as there's none provided for suggestions.

After writing the issue on #1  it asked for Jiraf version which was quite confusing to find out since GitHub was not updated with one and the further you go with new versions it could get confusing what version someone is on without being able to output one from Jiraf binary itself? So I was wondering if it would be a good idea to provide a internal jiraf version cmd e.g:

`jiraf version`

which would output the following:

> jiraf version CURRENT_VERSION_OF_BINARY_HERE

Thanks!

**Comment by gweithio** [comment]
Good Idea!, will implement this when I can

**Comment by gweithio** [comment]
Has since been added in v0.3.3
